### ISSUE TITLE
New config section property: 'inactive'

### ISSUE THREAD

**Issue by VicDeo** [m4x0nus/Multiplicator#10]
1. Config sections marked as `inactive:true` should be neither validated nor processed
2. Inactive property could be skipped, this means that the section is active.
e.g
```
out:
  section_1:
    skeleton: skel
  section_2:
    skeleton: skel
    inactive: true  # this makes section always valid and never processed
```

**Comment by VicDeo** [comment]
Most likely we don't need this as it could be workarounded this way:
```
out:
  section_1:
    skeleton: skel
    
inactive:
  section_2:
    skeleton: skel
```

Benefits of the latter approach: inactive and active sections are always sorted.
