### ISSUE TITLE
Global 'var' section 

### ISSUE THREAD

**Issue by VicDeo** [m4x0nus/Multiplicator#9]
Sample:

```
skeletons:

vars:
  - header: "my header"

out:
  - section_1:
    var:   # global 'header' var is available here
      name1: value
      
  - section_2:
    var:
      name1: value
      header: "custom header"  # This value takes precedence over the global value
      
```
